[package]
name = "zusi-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros"] }
tokio-util = { version = "0.7.3", features = ["codec"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
